# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV

development:
  secret_key_base: <%= Figaro.env.secret_key_base %>

######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>

######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>

######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV






# Heroku Specifics

######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV

heroku_dev:
  secret_key_base: <%= Figaro.env.secret_key_base %>

######## WARNING!! THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT SECRET KEYS IN HERE. REFER TO THE FIGARO ENV

heroku_prod:
  secret_key_base: <%= Figaro.env.secret_key_base %>
